# genseqn; configuration file: config/config.yaml

# General settings
sample_path: /path/to/dataset/ # Path to folder with sample directories (e.g. smpl_01/ont/ontfile.fastq.gz; smpl_01/illumina/illuminafile_1.fastq; smpl_01/illumina/illuminafile_2.fastq)
project_name: project_name # Project name for your samples (e.g. drosophila_samples)
save_dict: true # Save JSON dictionary file with sample information
illumina_data: true # Enable (true) or disable (false) Illumina data usage
fastqc_memory: "12000" # FASTQC memory in MB (minimum recommended: 8000)
pilon_memory: "32G" # Pilon Java heap memory (minimum recommended: 8G)

# Analyse settings
canu_genome_size: "12m" # Canu genomeSize parameter; determines expected genome size
canu_minInputCoverage: "" # Canu minInputCoverage; default = 10 if empty
canu_stopOnLowCoverage: "" # Canu stopOnLowCoverage; default = 0 if empty
canu_grid: "false" # Canu useGrid (true/false); enable cluster execution
busco_mode: "genome" # BUSCO mode; leave as "genome" for genome analyses
busco_lineage: "eukaryota_odb10" # BUSCO lineage dataset (see https://busco.ezlab.org/list_of_lineages.html)
